server:
  port: 8763
spring:
  application:
    name: customer
eureka:
  client:
    serviceUrl:
      defaultZone: http://xpshi:123456@localhost:8761/eureka
  instance:
    instance-id: customer-8763
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
