server:
  port: 8762
spring:
  application:
    name: order
eureka:
  client:
    serviceUrl:
      defaultZone: http://xpshi:123456@localhost:8761/eureka
  instance:
    instance-id: order-8762
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
