server:
  port: 8762
spring:
  application:
    name: order
eureka:
  client:
    serviceUrl:
      defaultZone: http://xpshi:123456@localhost:8761/eureka
    # 用于开启健康检查
    healthcheck:
      enabled: true
  instance:
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    # 采用IP注册
    prefer-ip-address: true
    # 自定义上面ip点击后跳转的地址
    statusPageUrl: c.biancheng.net
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    # 自定义一个简单的元数据
    metadata-map.biancheng: zhangsan

