server:
  port: 9000
spring:
  application:
    name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: gateway-9000
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
zuul:
  routes:
    order:
      serviceId: order
      path: /api/order/**
    customer:
      serviceId: customer
      path: /api/customer/**

